apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
      annotations:
        deployment.timestamp: "DEPLOYMENT_TIMESTAMP_PLACEHOLDER"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: DEPLOYMENT_TIME
          value: "DEPLOYMENT_TIMESTAMP_PLACEHOLDER"
        - name: BUILD_ID
          value: "BUILD_ID_PLACEHOLDER"
      tolerations:
        - key: role
          operator: Equal
          value: app-1323-std
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - app-1323-std
